permissions:
  contents: read
  id-token: write  # OIDC 권한 추가

steps:
  - uses: actions/checkout@v4
  - uses: denoland/setup-deno@v1
    with:
      deno-version: "2.1.4"
  - name: Publish package
    run: deno publish --check=all