name: Publish

on:
 push:
   tags:
     - 'v*'

permissions:
 contents: read

jobs:
 publish:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     
     - uses: denoland/setup-deno@v1
       with:
         deno-version: "2.1.4"
     
     - name: Check formatting
       run: deno fmt --check
     
     - name: Run linter
       run: deno lint
     
     - name: Run tests
       run: deno test
     
     - name: Publish package
       env:
         JSR_TOKEN: ${{ secrets.JSR_TOKEN }}
       run: deno publish